namespace BlazingStory.Docs.Models;

/// <summary>
/// One entry of the "On this page" outline.
/// </summary>
/// <param name="Id">The anchor identifier generated by the Markdown auto identifier extension.</param>
/// <param name="Text">The plain text of the heading.</param>
/// <param name="Level">The heading level, either 2 or 3.</param>
public sealed record TocEntry(string Id, string Text, int Level);
